spring:
  devtools:
    livereload:
      enabled: true
#   datasource:
#     url: jdbc:mysql://192.168.0.22:3306/rollin?serverTimezone=UTC&characterEncoding=UTF-8
#     username: rollin
#     password: 1234
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jwt:
  secret_key: SECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEY
  expTime: 86400000
